export const STATS = {
  totalReviews: 1289,
  averageRating: 4.9,
  fiveStarPct: 94,
  repeatCustomerPct: 78,
  countriesServed: 12,
}

export const FEATURED_REVIEWS = [
  {
    id: 1,
    name: 'Mrinali AB',
    location: 'Mumbai, Maharashtra',
    rating: 5,
    product: 'Venetian Maroon Golden Zari Kanjivaram',
    shortQuote: 'Simply the Best.',
    fullReview: 'My first purchase from House of Urvaah turned out best than expected. Loved the saree — quality is amazing. Highly recommend.',
    date: 'July 2025',
    avatarInitials: 'MA',
    avatarColor: '#6B1F2A',
    cardAccent: '#C9A84C',
    verified: true,
  },
  {
    id: 2,
    name: 'Mrinali R',
    location: 'Bangalore, Karnataka',
    rating: 5,
    product: 'Barbie Pink Golden Zari Kanjivaram',
    shortQuote: '10/10 Experience.',
    fullReview: 'I wore this saree for my Roka Ceremony. The quality was worth the price. Everybody loved it. Prompt customer service — great experience.',
    date: 'August 2025',
    avatarInitials: 'MR',
    avatarColor: '#E8B4B8',
    cardAccent: '#E8B4B8',
    verified: true,
  },
  {
    id: 3,
    name: 'Ruth Reji Philip',
    location: 'Kerala',
    rating: 5,
    product: 'Persian Red Golden Zari Kanjivaram',
    shortQuote: 'Very happy with the purchase.',
    fullReview: 'Always scared to buy from Instagram, but I am not disappointed. Quality is amazing and colour is true to the picture. Thank you!',
    date: 'August 2025',
    avatarInitials: 'RR',
    avatarColor: '#C9A84C',
    cardAccent: '#C9A84C',
    verified: true,
  },
  {
    id: 4,
    name: 'Snehal P',
    location: 'Pune, Maharashtra',
    rating: 5,
    product: 'Venetian Maroon Golden Zari Kanjivaram',
    shortQuote: 'Most beautiful saree I own.',
    fullReview: 'Most beautiful saree I have owned till now. The zari work is intricate and the fabric drapes perfectly. Will buy again.',
    date: 'November 2025',
    avatarInitials: 'SP',
    avatarColor: '#2D9B6E',
    cardAccent: '#2D9B6E',
    verified: true,
  },
  {
    id: 5,
    name: 'Kavya Prakash',
    location: 'Chennai, Tamil Nadu',
    rating: 5,
    product: 'Rust Orange Banarasi Satin Silk',
    shortQuote: 'Perfect for any festive occasion.',
    fullReview: 'The saree is super soft and drapes like a glove. It is totally worth the price and I will definitely be purchasing more.',
    date: 'April 2025',
    avatarInitials: 'KP',
    avatarColor: '#F5C518',
    cardAccent: '#F0A060',
    verified: true,
  },
  {
    id: 6,
    name: 'Sriram N',
    location: 'Hyderabad, Telangana',
    rating: 5,
    product: 'Pink Kanjivaram Tissue Silk Saree',
    shortQuote: 'This saree looks like an art.',
    fullReview: 'Worth every rupee. The saree looks like a work of art. Kudos to the designer, maker, and the whole team. Beautiful product.',
    date: 'October 2025',
    avatarInitials: 'SN',
    avatarColor: '#7B5CF0',
    cardAccent: '#C4B5FD',
    verified: true,
  },
]

export const MOSAIC_REVIEWS = [
  ...FEATURED_REVIEWS,
  { id:7, name:'Pinkii S', rating:5, product:'Barbie Pink Kanjivaram', shortQuote:'5 stars are not enough.', date:'August 2025', avatarInitials:'PS', avatarColor:'#E8B4B8', cardAccent:'#E8B4B8', verified:true },
  { id:8, name:'Sunidhi J', rating:5, product:'Teal Blue Banarasi Satin', shortQuote:'Worth buying. Looks great!', date:'April 2025', avatarInitials:'SJ', avatarColor:'#2D9B6E', cardAccent:'#2D9B6E', verified:true },
  { id:9, name:'Aarti Roy', rating:5, product:'Coral Peach Satin Silk', shortQuote:'Fabric and design are just perfect.', date:'July 2025', avatarInitials:'AR', avatarColor:'#F0A060', cardAccent:'#F0A060', verified:true },
  { id:10, name:'Kalpana P', rating:5, product:'Wild Strawberry Pink Kanjivaram', shortQuote:'Good product. Very good.', date:'March 2025', avatarInitials:'KP', avatarColor:'#C9A84C', cardAccent:'#C9A84C', verified:true },
  { id:11, name:'Mini S', rating:5, product:'Feather Soft Saree', shortQuote:'Best saree. Very good fabric.', date:'October 2025', avatarInitials:'MS', avatarColor:'#6B1F2A', cardAccent:'#C9A84C', verified:true },
  { id:12, name:'Preksha M', rating:5, product:'Raspberry Pink Kanjivaram', shortQuote:'I now trust only House of Urvaah.', date:'April 2025', avatarInitials:'PM', avatarColor:'#7B5CF0', cardAccent:'#C4B5FD', verified:true },
]
